name: test action

on:
  workflow_dispatch:
  push:

jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
      instance_id: ${{ steps.create-runner.outputs.instance_id }}
    steps:
      - name: Write yc key to file
        run: echo "${{ secrets.YC_KEYFILE }}" | base64 -d > yc-keyfile.json

      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            yandexcloud
            grpcio

      - id: create-runner
        uses: tf-cloud-test/yc-github-runner@master
        with:
          github_auth_token: ${{ secrets.PAT_GITHUB }}
          folder_id: ${{ secrets.FOLDER_ID }}
          sa_json_path: yc-keyfile.json
          runner_sa: ajevn4hv0j71arsnvo3b
          image_family: actions-runner
          subnet_id: e9b2av9mp3qfvu6pglr7

  test:
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - run: echo "This runs on the YC runner VM"

      - name: Write yc key to file
        run: echo "${{ secrets.YC_KEYFILE }}" | base64 -d > yc-keyfile.json

  remove-runner:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            yandexcloud
            grpcio

      - id: stop-runner
        uses: tf-cloud-test/yc-github-runner@master
        with:
          action: stop
          github_auth_token: ${{ secrets.PAT_GITHUB }}
          sa_json_path: yc-keyfile.json
          instance_id: ${{ needs.create-runner.outputs.instance_id }}
        if: always()
